version: "3.8"

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    build:
      context: ./../docker
      dockerfile: development/php-fpm/Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    container_name: ${COMPOSE_PROJECT_NAME}-php-cli
    build:
      context: ./../docker
      dockerfile: development/php-cli/Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Консьюмер очереди. Заменить  api-some-consumer, queue_name
  api-event-consumer:
    container_name: ${COMPOSE_PROJECT_NAME}-api-event-consumer
    build:
      context: ./../docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/app
    command: sh -c "wait-for-it rabbitmq:5672 -t 60 && sleep 1 && php bin/console messenger:consume events --limit=200"
    restart: always


  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./../docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/app
    depends_on:
      - php-fpm

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    build:
      context: ./../docker
      dockerfile: development/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  rabbitmq:
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    build:
      context: ./../docker/development
      dockerfile: rabbitmq/Dockerfile
    ports:
      - ${RABBITMQ_PORT}:15672
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      #RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    #        - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

volumes:
  db_data: